default: &default
  adapter: postgresql
  encoding: unicode
  username: railsapp
  password: cartman14
  pool: 5

development:
  <<: *default
  database: railsapp_development

test:
  <<: *default
  database: railsapp_test

production:
  <<: *default
  database: railsapp_production
  username: railsapp
  password: <%= ENV['RAILSAPP_DATABASE_PASSWORD'] %>
